---
title: "Step2_DataClipping"
author: "E. Mendonsa"
date: "2026-04-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Packages and Site Name Set Up
```{r message=FALSE}

library(tidyverse)
library(data.table)
library(readr)
library(readxl)
library(dplyr)
library(lubridate)
library(fuzzyjoin)

siteName <- "Arnold"

```


Import Site Data and Site visit log (dates and times)
```{r}

SiteData <- read_rds(file = paste("siteData/",siteName,"_combo_raw.rds",sep=""))
spans <- read_excel("span.xlsx", col_types = c("text", 
    "date", "text", "text", "date", "date"))


```


Remove timestamps where sonde is "in air"
```{r}


#SiteData_clipped <- SiteData %>%
#  mutate(datetime = as.POSIXct(paste(`Date (MM/DD/YYYY)`, `Time (HH:mm:ss)`), format = "%Y-%m-%d %H:%M:%S"))


# 1. Convert dataframes to data.tables
setDT(SiteData)
setDT(spans)

# 2. Find indices of points that fall INSIDE any span
# We use which = TRUE to get row numbers instead of data
inside_indices <- SiteData[spans, 
                          on = .(DateTime >= start, DateTime <= stop), 
                          which = TRUE, 
                          nomatch = NULL]

# 2b. Record of the rows that fall INSIDE any span, using the non-equi join
# This looks for rows in df_data where 'time' is between 'start' and 'end'
inside_clippedRows <- SiteData[spans, 
                  on = .(DateTime <= start, DateTime >= stop), 
                  nomatch = NULL]

# 3. Filter the original data to keep only rows NOT in those indices
SiteData_clipped <- SiteData[-(inside_indices)]

```


Save as Rdata and Excel
```{r}

write.csv(SiteData_clipped, file = paste("siteData/",siteName,"_combo_clipped.csv",sep=""),row.names = FALSE)
write_rds(SiteData_clipped, file = paste("siteData/",siteName,"_combo_clipped.rds",sep=""))

```

